workflows:
  default-workflow:
    name: Default Workflow
    max_build_duration: 120
    instance_type: mac_mini_m2
    environment:
      flutter: stable
    triggering:
      events:
        - push
    scripts:
      - name: Create Android project structure
        script: |
          flutter create . --platforms=android
          mkdir -p android/app
          cp google-services.json android/app/
      - name: Get Flutter packages
        script: |
          flutter packages pub get
      - name: Build Android APK
        script: |
          flutter build apk --release
    artifacts:
      - build/app/outputs/flutter-apk/app-release.apk
      
